app = "multi-convo"   # <- yahan apna unique app name likhna

primary_region = "sin"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
