# fly.toml file generated for multi-convo

app = "multi-convo"   # yahan apne app ka naam likho (unique hona chahiye)

primary_region = "sin"   # nearest region (Pakistan ke liye Singapore best hai)

[build]
  # agar aap Dockerfile use karte ho to yahan kuch likhne ki zarurat nahi
  # agar Python app hai aur Dockerfile nahi hai to Fly.io auto-detect karega

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
